language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov

CODECOV_TOKEN='2909c3bb-29f9-4eda-8609-40a28e8b2d89'